Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -19,11 +19,16 @@ jobs:
       run: sudo rm -rf /home/ubuntu/actions-runner/_work/demo-3/demo-3/node_modules || true
 
     - uses: actions/checkout@v4
+
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
-    - run: npm install
+
+    - name: Check for package-lock.json
+      run: test -f package-lock.json || echo "Lock file not found!"
+
+    - run: npm ci
     - run: npm run build --if-present
     - run: pm2 restart demo
